### ISSUE TITLE
WindowsError: [Error 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by bommuuu** [dsoprea/PySvn#132]
I am using below code to checkout from svn.
import svn.utility

r = svn.utility.get_client("my_svn_url_path"\
                           ,trust_cert=True,username='*****',password='*****')
r.checkout(path = 'D:\SVN_Python_test')

I am getting below error.
C:\Python27\python.exe "C:/Users/sbommu/OneDrive - Apollo Fire Detectors Ltd/Automate_Everything/PythonScripts_Pycharm/SVN_Python_Test.py"
Traceback (most recent call last):
  File "C:/Users/sbommu/OneDrive - Apollo Fire Detectors Ltd/Automate_Everything/PythonScripts_Pycharm/SVN_Python_Test.py", line 5, in <module>
    r.checkout(path = 'D:\SVN_Python_test')
  File "C:\Python27\lib\site-packages\svn\remote.py", line 20, in checkout
    self.run_command('checkout', cmd)
  File "C:\Python27\lib\site-packages\svn\common.py", line 54, in run_command
    return self.external_command(cmd, environment=self.__env, **kwargs)
  File "C:\Python27\lib\site-packages\svn\common_base.py", line 25, in external_command
    env=env)
  File "C:\Python27\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

Process finished with exit code 1

**Comment by dsoprea** [comment]
The only thing we're trying to run is Subversion. So, make sure that "svn" is in your path. If not that, we're going to need more information.

It also seems like you're using both forward slashes and backward slashes in your paths. I'd encourage you to stay consistent. Plus, if you're using backslashes, make sure you're escaping them when used within quotes.
