### ISSUE TITLE
AttributeError when Author is None

### ISSUE THREAD

**Issue by TylerGubala** [dsoprea/PySvn#140]
OS: Windows 10 64bit
Python version: 3.5-32
PySvn version: 0.3.46

When attempting to list files in extended mode (`extended=True`) or recursively, an exception is thrown when the `commit_node.find('author') is None`. 

Example:

```python
#! /usr/bin/python
# -*- coding: utf-8 -*-
"""Basic example of issue where author nodes not being found breaks svn functionality
"""
from svn.remote import RemoteClient as SvnRepo  
blendersvn = SvnRepo("https://svn.blender.org/svnroot/bf-blender/")

for tag in blendersvn.list_recursive(rel_path="/tags"): 
     print(tag)
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\TGubs\Code\Python\bpymaketest\venvs\3.5-32\lib\site-packages\svn\common.py", line 396, in list_recursive
    for entry in self.list(extended=True, rel_path=current_rel_path):
  File "C:\Users\TGubs\Code\Python\bpymaketest\venvs\3.5-32\lib\site-packages\svn\common.py", line 363, in list
    author = commit_node.find('author').text
AttributeError: 'NoneType' object has no attribute 'text'
```

```python
#! /usr/bin/python
# -*- coding: utf-8 -*-
"""Basic example of issue where author nodes not being found breaks svn functionality
"""
from svn.remote import RemoteClient as SvnRepo  
blendersvn = SvnRepo("https://svn.blender.org/svnroot/bf-blender/")

for tag in blendersvn.list(rel_path="/tags", extended=True): 
     print(tag)
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\TGubs\Code\Python\bpymaketest\venvs\3.5-32\lib\site-packages\svn\common.py", line 363, in list
    author = commit_node.find('author').text
AttributeError: 'NoneType' object has no attribute 'text'
```

Possibly related is [a pull request from 2017](https://github.com/dsoprea/PySvn/pull/99) and issue #89

**Comment by mtHB** [comment]
I ran into the same problem. Have you found a solution @TylerGubala?

**Comment by TylerGubala** [comment]
My "solution" basically amounts to avoiding commits where the author is
returned as None.

I also have not looked very deeply into it. Hope you find better success!

**Comment by mtHB** [comment]
@TylerGubala You should not avoid commits where author is None.
While implementing the log_default method by myself I found out that a merge commit does not need a author.
The project I am working on does need an information like that.
