### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by isaacyoung** [dsoprea/PySvn#187]
code:
r = svn.remote.RemoteClient(url)
logs = r.log_default(stop_on_copy=True)

error:
Traceback (most recent call last):
  File "E:\PycharmProjects\branch\venv\lib\site-packages\svn\common_base.py", line 24, in external_command
    subprocess.check_output(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 495, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1015, in communicate
    stdout = self.stdout.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 5263: illegal multibyte sequence

**Comment by 20174103151** [comment]
https://github.com/dsoprea/PySvn/issues/176
